// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CornerStore.Migrations
{
    [DbContext(typeof(CornerStoreDbContext))]
    partial class CornerStoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CornerStore.Models.Cashier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Cashiers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Alice",
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Bob",
                            LastName = "Johnson"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Charlie",
                            LastName = "Williams"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "David",
                            LastName = "Brown"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Eve",
                            LastName = "Davis"
                        });
                });

            modelBuilder.Entity("CornerStore.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Clothing"
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Home Goods"
                        });
                });

            modelBuilder.Entity("CornerStore.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CashierId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PaidOnDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("CashierId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CashierId = 1,
                            PaidOnDate = new DateTime(2025, 5, 16, 10, 10, 58, 865, DateTimeKind.Local).AddTicks(1320)
                        },
                        new
                        {
                            Id = 2,
                            CashierId = 2,
                            PaidOnDate = new DateTime(2025, 5, 16, 10, 10, 58, 865, DateTimeKind.Local).AddTicks(1400)
                        },
                        new
                        {
                            Id = 3,
                            CashierId = 3,
                            PaidOnDate = new DateTime(2025, 5, 16, 10, 10, 58, 865, DateTimeKind.Local).AddTicks(1400)
                        },
                        new
                        {
                            Id = 4,
                            CashierId = 4,
                            PaidOnDate = new DateTime(2025, 5, 16, 10, 10, 58, 865, DateTimeKind.Local).AddTicks(1410)
                        },
                        new
                        {
                            Id = 5,
                            CashierId = 5,
                            PaidOnDate = new DateTime(2025, 5, 16, 10, 10, 58, 865, DateTimeKind.Local).AddTicks(1410)
                        },
                        new
                        {
                            Id = 6,
                            CashierId = 1,
                            PaidOnDate = new DateTime(2025, 5, 16, 10, 10, 58, 865, DateTimeKind.Local).AddTicks(1410)
                        },
                        new
                        {
                            Id = 7,
                            CashierId = 2,
                            PaidOnDate = new DateTime(2025, 5, 16, 10, 10, 58, 865, DateTimeKind.Local).AddTicks(1420)
                        },
                        new
                        {
                            Id = 8,
                            CashierId = 3,
                            PaidOnDate = new DateTime(2025, 5, 16, 10, 10, 58, 865, DateTimeKind.Local).AddTicks(1420)
                        },
                        new
                        {
                            Id = 9,
                            CashierId = 4,
                            PaidOnDate = new DateTime(2025, 5, 16, 10, 10, 58, 865, DateTimeKind.Local).AddTicks(1420)
                        },
                        new
                        {
                            Id = 10,
                            CashierId = 5,
                            PaidOnDate = new DateTime(2025, 5, 16, 10, 10, 58, 865, DateTimeKind.Local).AddTicks(1420)
                        },
                        new
                        {
                            Id = 11,
                            CashierId = 1,
                            PaidOnDate = new DateTime(2025, 5, 16, 10, 10, 58, 865, DateTimeKind.Local).AddTicks(1430)
                        },
                        new
                        {
                            Id = 12,
                            CashierId = 2,
                            PaidOnDate = new DateTime(2025, 5, 16, 10, 10, 58, 865, DateTimeKind.Local).AddTicks(1430)
                        });
                });

            modelBuilder.Entity("CornerStore.Models.OrderProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderProducts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderId = 1,
                            ProductId = 1,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 2,
                            OrderId = 1,
                            ProductId = 2,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 3,
                            OrderId = 2,
                            ProductId = 3,
                            Quantity = 3
                        },
                        new
                        {
                            Id = 4,
                            OrderId = 2,
                            ProductId = 4,
                            Quantity = 4
                        },
                        new
                        {
                            Id = 5,
                            OrderId = 3,
                            ProductId = 5,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 6,
                            OrderId = 3,
                            ProductId = 6,
                            Quantity = 6
                        },
                        new
                        {
                            Id = 7,
                            OrderId = 4,
                            ProductId = 7,
                            Quantity = 7
                        },
                        new
                        {
                            Id = 8,
                            OrderId = 4,
                            ProductId = 8,
                            Quantity = 8
                        },
                        new
                        {
                            Id = 9,
                            OrderId = 5,
                            ProductId = 9,
                            Quantity = 9
                        },
                        new
                        {
                            Id = 10,
                            OrderId = 5,
                            ProductId = 10,
                            Quantity = 10
                        },
                        new
                        {
                            Id = 11,
                            OrderId = 6,
                            ProductId = 1,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 12,
                            OrderId = 6,
                            ProductId = 3,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 13,
                            OrderId = 7,
                            ProductId = 5,
                            Quantity = 3
                        },
                        new
                        {
                            Id = 14,
                            OrderId = 7,
                            ProductId = 7,
                            Quantity = 4
                        },
                        new
                        {
                            Id = 15,
                            OrderId = 8,
                            ProductId = 9,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 16,
                            OrderId = 8,
                            ProductId = 2,
                            Quantity = 6
                        },
                        new
                        {
                            Id = 17,
                            OrderId = 9,
                            ProductId = 4,
                            Quantity = 7
                        },
                        new
                        {
                            Id = 18,
                            OrderId = 9,
                            ProductId = 6,
                            Quantity = 8
                        },
                        new
                        {
                            Id = 19,
                            OrderId = 10,
                            ProductId = 8,
                            Quantity = 9
                        },
                        new
                        {
                            Id = 20,
                            OrderId = 10,
                            ProductId = 10,
                            Quantity = 10
                        },
                        new
                        {
                            Id = 21,
                            OrderId = 11,
                            ProductId = 2,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 22,
                            OrderId = 11,
                            ProductId = 4,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 23,
                            OrderId = 12,
                            ProductId = 6,
                            Quantity = 3
                        },
                        new
                        {
                            Id = 24,
                            OrderId = 12,
                            ProductId = 8,
                            Quantity = 4
                        });
                });

            modelBuilder.Entity("CornerStore.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Generic",
                            CategoryId = 1,
                            Price = 1200.00m,
                            ProductName = "Laptop"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Generic",
                            CategoryId = 1,
                            Price = 800.00m,
                            ProductName = "Smartphone"
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Generic",
                            CategoryId = 2,
                            Price = 25.00m,
                            ProductName = "T-Shirt"
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Generic",
                            CategoryId = 2,
                            Price = 75.00m,
                            ProductName = "Jeans"
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Generic",
                            CategoryId = 3,
                            Price = 60.00m,
                            ProductName = "Coffee Maker"
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Generic",
                            CategoryId = 3,
                            Price = 45.00m,
                            ProductName = "Blender"
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Generic",
                            CategoryId = 1,
                            Price = 300.00m,
                            ProductName = "Tablet"
                        },
                        new
                        {
                            Id = 8,
                            Brand = "Generic",
                            CategoryId = 2,
                            Price = 120.00m,
                            ProductName = "Jacket"
                        },
                        new
                        {
                            Id = 9,
                            Brand = "Generic",
                            CategoryId = 3,
                            Price = 30.00m,
                            ProductName = "Toaster"
                        },
                        new
                        {
                            Id = 10,
                            Brand = "Generic",
                            CategoryId = 1,
                            Price = 150.00m,
                            ProductName = "Headphones"
                        });
                });

            modelBuilder.Entity("CornerStore.Models.Order", b =>
                {
                    b.HasOne("CornerStore.Models.Cashier", "Cashier")
                        .WithMany("Orders")
                        .HasForeignKey("CashierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cashier");
                });

            modelBuilder.Entity("CornerStore.Models.OrderProduct", b =>
                {
                    b.HasOne("CornerStore.Models.Order", "Order")
                        .WithMany("OrderProducts")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CornerStore.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CornerStore.Models.Product", b =>
                {
                    b.HasOne("CornerStore.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CornerStore.Models.Cashier", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("CornerStore.Models.Order", b =>
                {
                    b.Navigation("OrderProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
